title: "Faceloader"
description: "A simple gui application to create ical files with events from Facebook pages."
permalink: pretty
exclude:
  - dist
  - parser
  - .github
  - "*.go"
  - go.mod
  - go.sum
  - Icon.png
  - ".*.yml"
remote_theme: just-the-docs/just-the-docs
search_enabled: false
aux_links:
  "Download":
    - "https://github.com/geeksforsocialchange/faceloader/releases/latest"
  "Source Code":
    - "https://github.com/geeksforsocialchange/faceloader"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/geeksforsocialchange/faceloader"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"